spring.application.name=integration-api-demo
server.address=127.0.0.1
server.port=2180
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha
kakao.api.base-url=https://dapi.kakao.com
kakao.api.key=${KAKAO_REST_API_KEY:}
spring.config.import=optional:file:./.env[.properties]
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/integration_demo}
spring.datasource.username=${DB_USERNAME:demo_user}
spring.datasource.password=${DB_PASSWORD}
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.default-statement-timeout=10
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/schema.sql
