spring.application.name=integration-api-demo
server.address=127.0.0.1
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha
kakao.api.base-url=https://dapi.kakao.com
kakao.api.key=${KAKAO_REST_API_KEY:}
