-- 로컬 데모 초기화용. 기존 테이블/행을 삭제하거나 변경하지 않는다.
CREATE TABLE IF NOT EXISTS favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn VARCHAR(13) NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    publisher TEXT,
    thumbnail TEXT,
    url TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_favorites_isbn UNIQUE (isbn)
);

CREATE TABLE IF NOT EXISTS favorite_authors (
    favorite_id BIGINT NOT NULL,
    author_order INTEGER NOT NULL,
    author TEXT,
    PRIMARY KEY (favorite_id, author_order),
    CONSTRAINT fk_favorite_authors_favorite FOREIGN KEY (favorite_id) REFERENCES favorites (id)
);
